# Generated by Django 2.1.5 on 2019-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domirecord', '0002_auto_20190313_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('card_onoff', models.BooleanField()),
                ('wikilink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('event_onoff', models.BooleanField()),
                ('wikilink', models.CharField(max_length=200)),
            ],
        ),
    ]
