# Generated by Django 2.1.5 on 2019-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domirecord', '0003_card_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_onoff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_onoff',
            field=models.BooleanField(default=True),
        ),
    ]
