# Generated by Django 2.1.5 on 2019-03-14 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domirecord', '0004_auto_20190314_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(max_length=200)),
                ('player', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=100)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
