# Generated by Django 2.1.5 on 2019-03-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domirecord', '0008_result_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.CharField(default='kamenbutokai', max_length=200),
        ),
    ]
