# Generated by Django 2.1.5 on 2019-03-28 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('card_onoff', models.BooleanField(default=True)),
                ('wikilink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('event_onoff', models.BooleanField(default=True)),
                ('wikilink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_onoff', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
