# Generated by Django 2.1.5 on 2019-03-28 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domirecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('基本', models.BooleanField(default=True)),
                ('陰謀', models.BooleanField(default=True)),
                ('海辺', models.BooleanField(default=True)),
                ('錬金術', models.BooleanField(default=True)),
                ('繁栄', models.BooleanField(default=True)),
                ('収穫祭', models.BooleanField(default=True)),
                ('異郷', models.BooleanField(default=True)),
                ('暗黒時代', models.BooleanField(default=True)),
                ('ギルド', models.BooleanField(default=True)),
                ('冒険', models.BooleanField(default=True)),
                ('帝国', models.BooleanField(default=True)),
                ('夜想曲', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
