# Generated by Django 2.1.5 on 2019-03-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domirecord', '0002_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='冒険',
            new_name='adventures',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='錬金術',
            new_name='alchemy',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='基本',
            new_name='basic',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='収穫祭',
            new_name='cornucopia',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='暗黒時代',
            new_name='darkage',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='帝国',
            new_name='empires',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='ギルド',
            new_name='guild',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='異郷',
            new_name='hinterlands',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='陰謀',
            new_name='intrigue',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='夜想曲',
            new_name='nocturne',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='繁栄',
            new_name='prosperity',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='海辺',
            new_name='seaside',
        ),
    ]
