from .models import Card,Event

cardlist=[['地下貯蔵庫',
  '2',
  'アクション',
  '基本',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/地下貯蔵庫'],
 ['礼拝堂', '2', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/礼拝堂'],
 ['堀',
  '2',
  'アクション-リアクション',
  '基本',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/堀'],
 ['家臣', '3', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/家臣'],
 ['工房', '3', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/工房'],
 ['商人', '3', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/商人'],
 ['前駆者', '3', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/前駆者'],
 ['村', '3', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/村'],
 ['改築', '4', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/改築'],
 ['鍛冶屋', '4', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/鍛冶屋'],
 ['金貸し', '4', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/金貸し'],
 ['玉座の間',
  '4',
  'アクション',
  '基本',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/玉座の間'],
 ['密猟者', '4', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/密猟者'],
 ['民兵',
  '4',
  'アクション-アタック',
  '基本',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/民兵'],
 ['役人',
  '4',
  'アクション-アタック',
  '基本',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/役人'],
 ['庭園', '4', '勝利点', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/庭園'],
 ['市場', '5', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/市場'],
 ['衛兵', '5', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/衛兵'],
 ['議事堂', '5', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/議事堂'],
 ['研究所', '5', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/研究所'],
 ['鉱山', '5', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/鉱山'],
 ['祝祭', '5', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/祝祭'],
 ['書庫', '5', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/書庫'],
 ['山賊',
  '5',
  'アクション-アタック',
  '基本',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/山賊'],
 ['魔女',
  '5',
  'アクション-アタック',
  '基本',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/魔女'],
 ['職人', '6', 'アクション', '基本', '', True, 'https://wikiwiki.jp/dominiondeck/職人'],
 ['手先', '2', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/手先'],
 ['中庭', '2', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/中庭'],
 ['秘密の部屋',
  '2',
  'アクション-リアクション',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/秘密の部屋'],
 ['仮面舞踏会',
  '3',
  'アクション',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/仮面舞踏会'],
 ['執事', '3', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/執事'],
 ['願いの井戸',
  '3',
  'アクション',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/願いの井戸'],
 ['貧民街', '3', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/貧民街'],
 ['詐欺師',
  '3',
  'アクション-アタック',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/詐欺師'],
 ['大広間', '3', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/大広間'],
 ['共謀者', '4', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/共謀者'],
 ['鉱山の村',
  '4',
  'アクション',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/鉱山の村'],
 ['男爵', '4', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/男爵'],
 ['偵察員', '4', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/偵察員'],
 ['鉄工所', '4', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/鉄工所'],
 ['銅細工師',
  '4',
  'アクション',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/銅細工師'],
 ['橋', '4', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/橋'],
 ['改良', '5', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/改良'],
 ['交易場', '5', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/交易場'],
 ['貢物', '5', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/貢物'],
 ['拷問人',
  '5',
  'アクション-アタック',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/拷問人'],
 ['寵臣',
  '5',
  'アクション-アタック',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/寵臣'],
 ['破壊工作員',
  '5',
  'アクション-アタック',
  '陰謀',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/破壊工作員'],
 ['公爵', '5', '勝利点', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/公爵'],
 ['貴族', '6', 'アクション', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/貴族'],
 ['ハーレム', '6', '財宝', '陰謀', '', True, 'https://wikiwiki.jp/dominiondeck/ハーレム'],
 ['原住民の村',
  '2',
  'アクション',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/原住民の村'],
 ['真珠採り',
  '2',
  'アクション',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/真珠採り'],
 ['抑留', '2', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/抑留'],
 ['停泊所',
  '2',
  'アクション-持続',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/停泊所'],
 ['灯台',
  '2',
  'アクション-持続',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/灯台'],
 ['倉庫', '3', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/倉庫'],
 ['密輸人', '3', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/密輸人'],
 ['見張り', '3', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/見張り'],
 ['大使',
  '3',
  'アクション-アタック',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/大使'],
 ['漁村',
  '3',
  'アクション-持続',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/漁村'],
 ['航海士', '4', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/航海士'],
 ['宝の地図',
  '4',
  'アクション',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/宝の地図'],
 ['引揚水夫',
  '4',
  'アクション',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/引揚水夫'],
 ['海の妖婆',
  '4',
  'アクション-アタック',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/海の妖婆'],
 ['海賊船',
  '4',
  'アクション-アタック',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/海賊船'],
 ['巾着切り',
  '4',
  'アクション-アタック',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/巾着切り'],
 ['隊商',
  '4',
  'アクション-持続',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/隊商'],
 ['島', '4', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/島'],
 ['探検家', '5', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/探検家'],
 ['バザー', '5', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/バザー'],
 ['宝物庫', '5', 'アクション', '海辺', '', True, 'https://wikiwiki.jp/dominiondeck/宝物庫'],
 ['幽霊船',
  '5',
  'アクション-アタック',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/幽霊船'],
 ['前哨地',
  '5',
  'アクション-持続',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/前哨地'],
 ['策士',
  '5',
  'アクション-持続',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/策士'],
 ['商船',
  '5',
  'アクション-持続',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/商船'],
 ['船着場',
  '5',
  'アクション-持続',
  '海辺',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/船着場'],
 ['薬草商',
  '2',
  'アクション',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/薬草商'],
 ['弟子', '5', 'アクション', '錬金術', '', True, 'https://wikiwiki.jp/dominiondeck/弟子'],
 ['変成', 'P', 'アクション', '錬金術', '', True, 'https://wikiwiki.jp/dominiondeck/変成'],
 ['ブドウ園',
  'P',
  '勝利点',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ブドウ園'],
 ['薬師',
  '2+P',
  'アクション',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/薬師'],
 ['大学',
  '2+P',
  'アクション',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/大学'],
 ['念視の泉',
  '2+P',
  'アクション-アタック',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/念視の泉'],
 ['錬金術師',
  '3+P',
  'アクション',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/錬金術師'],
 ['使い魔',
  '3+P',
  'アクション-アタック',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/使い魔'],
 ['賢者の石',
  '3+P',
  '財宝',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/賢者の石'],
 ['ゴーレム',
  '4+P',
  'アクション',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ゴーレム'],
 ['支配',
  '6+P',
  'アクション',
  '錬金術',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/支配'],
 ['交易路', '3', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/交易路'],
 ['望楼',
  '3',
  'アクション-リアクション',
  '繁栄',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/望楼'],
 ['借金', '3', '財宝', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/借金'],
 ['記念碑', '4', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/記念碑'],
 ['司教', '4', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/司教'],
 ['労働者の村',
  '4',
  'アクション',
  '繁栄',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/労働者の村'],
 ['護符', '4', '財宝', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/護符'],
 ['石切場', '4', '財宝', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/石切場'],
 ['会計所', '5', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/会計所'],
 ['造幣所', '5', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/造幣所'],
 ['都市', '5', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/都市'],
 ['保管庫', '5', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/保管庫'],
 ['大衆',
  '5',
  'アクション-アタック',
  '繁栄',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/大衆'],
 ['香具師',
  '5',
  'アクション-アタック',
  '繁栄',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/香具師'],
 ['玉璽', '5', '財宝', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/玉璽'],
 ['禁制品', '5', '財宝', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/禁制品'],
 ['投機', '5', '財宝', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/投機'],
 ['大市場', '6', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/大市場'],
 ['ならず者',
  '6',
  'アクション-アタック',
  '繁栄',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ならず者'],
 ['隠し財産', '6', '財宝', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/隠し財産'],
 ['拡張', '7', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/拡張'],
 ['宮廷', '7', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/宮廷'],
 ['鍛造', '7', 'アクション', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/鍛造'],
 ['銀行', '7', '財宝', '繁栄', '', True, 'https://wikiwiki.jp/dominiondeck/銀行'],
 ['行商人',
  '8*',
  'アクション',
  '繁栄',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/行商人'],
 ['村落', '2', 'アクション', '収穫祭', '', True, 'https://wikiwiki.jp/dominiondeck/村落'],
 ['移動動物園',
  '3',
  'アクション',
  '収穫祭',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/移動動物園'],
 ['占い師',
  '3',
  'アクション-アタック',
  '収穫祭',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/占い師'],
 ['再建', '4', 'アクション', '収穫祭', '', True, 'https://wikiwiki.jp/dominiondeck/再建'],
 ['農村', '4', 'アクション', '収穫祭', '', True, 'https://wikiwiki.jp/dominiondeck/農村'],
 ['馬上槍試合',
  '4',
  'アクション',
  '収穫祭',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/馬上槍試合'],
 ['魔女娘',
  '4',
  'アクション-アタック',
  '収穫祭',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/魔女娘'],
 ['馬商人',
  '4',
  'アクション-リアクション',
  '収穫祭',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/馬商人'],
 ['収穫', '5', 'アクション', '収穫祭', '', True, 'https://wikiwiki.jp/dominiondeck/収穫'],
 ['狩猟団',
  '5',
  'アクション',
  '収穫祭',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/狩猟団'],
 ['道化師',
  '5',
  'アクション-アタック',
  '収穫祭',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/道化師'],
 ['豊穣の角笛',
  '5',
  '財宝',
  '収穫祭',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/豊穣の角笛'],
 ['品評会', '6', '勝利点', '収穫祭', '', True, 'https://wikiwiki.jp/dominiondeck/品評会'],
 ['岐路', '2', 'アクション', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/岐路'],
 ['公爵夫人',
  '2',
  'アクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/公爵夫人'],
 ['愚者の黄金',
  '2',
  '財宝',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/愚者の黄金'],
 ['オアシス',
  '3',
  'アクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/オアシス'],
 ['開発', '3', 'アクション', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/開発'],
 ['画策', '3', 'アクション', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/画策'],
 ['神託',
  '3',
  'アクション-アタック',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/神託'],
 ['坑道', '3', '勝利点', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/坑道'],
 ['香辛料商人',
  '4',
  'アクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/香辛料商人'],
 ['遊牧民の野営地',
  '4',
  'アクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/遊牧民の野営地'],
 ['よろずや',
  '4',
  'アクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/よろずや'],
 ['義賊',
  '4',
  'アクション-アタック',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/義賊'],
 ['交易人',
  '4',
  'アクション-リアクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/交易人'],
 ['シルクロード',
  '4',
  '勝利点',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/シルクロード'],
 ['街道', '5', 'アクション', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/街道'],
 ['官吏', '5', 'アクション', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/官吏'],
 ['厩舎', '5', 'アクション', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/厩舎'],
 ['大使館', '5', 'アクション', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/大使館'],
 ['地図職人',
  '5',
  'アクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/地図職人'],
 ['値切り屋',
  '5',
  'アクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/値切り屋'],
 ['宿屋', '5', 'アクション', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/宿屋'],
 ['辺境伯',
  '5',
  'アクション-アタック',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/辺境伯'],
 ['不正利得', '5', '財宝', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/不正利得'],
 ['埋蔵金', '5', '財宝', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/埋蔵金'],
 ['国境の村',
  '6',
  'アクション',
  '異郷',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/国境の村'],
 ['農地', '6', '勝利点', '異郷', '', True, 'https://wikiwiki.jp/dominiondeck/農地'],
 ['救貧院',
  '1',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/救貧院'],
 ['従者', '2', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/従者'],
 ['浮浪者',
  '2',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/浮浪者'],
 ['物乞い',
  '2',
  'アクション-リアクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/物乞い'],
 ['隠遁者',
  '3',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/隠遁者'],
 ['賢者', '3', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/賢者'],
 ['採集者',
  '3',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/採集者'],
 ['物置', '3', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/物置'],
 ['浮浪児',
  '3',
  'アクション-アタック',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/浮浪児'],
 ['青空市場',
  '3',
  'アクション-リアクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/青空市場'],
 ['金物商',
  '4',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/金物商'],
 ['吟遊詩人',
  '4',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/吟遊詩人'],
 ['行進', '4', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/行進'],
 ['ゴミあさり',
  '4',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ゴミあさり'],
 ['城塞', '4', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/城塞'],
 ['ネズミ',
  '4',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ネズミ'],
 ['武器庫',
  '4',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/武器庫'],
 ['死の荷車',
  '4',
  'アクション-略奪者',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/死の荷車'],
 ['襲撃者',
  '4',
  'アクション-アタック-略奪者',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/襲撃者'],
 ['封土', '4', '勝利点', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/封土'],
 ['屑屋', '5', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/屑屋'],
 ['山賊の宿営地',
  '5',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/山賊の宿営地'],
 ['建て直し',
  '5',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/建て直し'],
 ['地下墓所',
  '5',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/地下墓所'],
 ['墓暴き',
  '5',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/墓暴き'],
 ['伯爵', '5', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/伯爵'],
 ['はみだし者',
  '5',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/はみだし者'],
 ['秘術師',
  '5',
  'アクション',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/秘術師'],
 ['盗賊',
  '5',
  'アクション-アタック',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/盗賊'],
 ['略奪',
  '5',
  'アクション-アタック',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/略奪'],
 ['狂信者',
  '5',
  'アクション-アタック-略奪者',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/狂信者'],
 ['騎士',
  '5',
  'アクション-アタック-騎士',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/騎士'],
 ['偽造通貨',
  '5',
  '財宝',
  '暗黒時代',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/偽造通貨'],
 ['狩場', '6', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/狩場'],
 ['祭壇', '6', 'アクション', '暗黒時代', '', True, 'https://wikiwiki.jp/dominiondeck/祭壇'],
 ['蝋燭職人',
  '2',
  'アクション',
  'ギルド',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/蝋燭職人'],
 ['石工', '2+', 'アクション', 'ギルド', '', True, 'https://wikiwiki.jp/dominiondeck/石工'],
 ['医者', '3+', 'アクション', 'ギルド', '', True, 'https://wikiwiki.jp/dominiondeck/医者'],
 ['名品', '3+', '財宝', 'ギルド', '', True, 'https://wikiwiki.jp/dominiondeck/名品'],
 ['助言者',
  '4',
  'アクション',
  'ギルド',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/助言者'],
 ['広場', '4', 'アクション', 'ギルド', '', True, 'https://wikiwiki.jp/dominiondeck/広場'],
 ['収税吏',
  '4',
  'アクション-アタック',
  'ギルド',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/収税吏'],
 ['伝令官',
  '4+',
  'アクション',
  'ギルド',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/伝令官'],
 ['熟練工',
  '5',
  'アクション',
  'ギルド',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/熟練工'],
 ['商人ギルド',
  '5',
  'アクション',
  'ギルド',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/商人ギルド'],
 ['肉屋', '5', 'アクション', 'ギルド', '', True, 'https://wikiwiki.jp/dominiondeck/肉屋'],
 ['パン屋',
  '5',
  'アクション',
  'ギルド',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/パン屋'],
 ['予言者',
  '5',
  'アクション-アタック',
  'ギルド',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/予言者'],
 ['倒壊', '2', 'アクション', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/倒壊'],
 ['鼠取り',
  '2',
  'アクション-リザーブ',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/鼠取り'],
 ['法貨', '2', '財宝', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/法貨'],
 ['地下牢',
  '3',
  'アクション-持続',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/地下牢'],
 ['道具',
  '3',
  'アクション-持続',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/道具'],
 ['魔除け',
  '3',
  'アクション-持続',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/魔除け'],
 ['隊商の護衛',
  '3',
  'アクション-持続',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/隊商の護衛'],
 ['案内人',
  '3',
  'アクション-リザーブ',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/案内人'],
 ['カササギ',
  '4',
  'アクション',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/カササギ'],
 ['使者', '4', 'アクション', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/使者'],
 ['守銭奴', '4', 'アクション', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/守銭奴'],
 ['港町', '4', 'アクション', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/港町'],
 ['山守', '4', 'アクション', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/山守'],
 ['複製',
  '4',
  'アクション-リザーブ',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/複製'],
 ['変容',
  '4',
  'アクション-リザーブ',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/変容'],
 ['失われし都市',
  '5',
  'アクション',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/失われし都市'],
 ['語り部', '5', 'アクション', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/語り部'],
 ['工匠', '5', 'アクション', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/工匠'],
 ['巨人',
  '5',
  'アクション-アタック',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/巨人'],
 ['沼の妖婆',
  '5',
  'アクション-アタック',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/沼の妖婆'],
 ['呪いの森',
  '5',
  'アクション-アタック',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/呪いの森'],
 ['橋の下のトロル',
  '5',
  'アクション-アタック',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/橋の下のトロル'],
 ['御料車',
  '5',
  'アクション-リザーブ',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/御料車'],
 ['ワイン商',
  '5',
  'アクション-リザーブ',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ワイン商'],
 ['遠隔地',
  '5',
  'アクション-リザーブ',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/遠隔地'],
 ['掘出物', '5', '財宝', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/掘出物'],
 ['遺物', '5', '財宝', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/遺物'],
 ['雇人',
  '6',
  'アクション-持続',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/雇人'],
 ['戦車競走',
  '3',
  'アクション',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/戦車競走'],
 ['農家の市場',
  '3',
  'アクション-集合',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/農家の市場'],
 ['女魔術師',
  '3',
  'アクション-アタック',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/女魔術師'],
 ['生贄', '4', 'アクション', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/生贄'],
 ['ヴィラ', '4', 'アクション', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/ヴィラ'],
 ['公共広場',
  '5',
  'アクション',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/公共広場'],
 ['ワイルドハント',
  '5',
  'アクション-集合',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ワイルドハント'],
 ['軍団兵',
  '5',
  'アクション-アタック',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/軍団兵'],
 ['資料庫',
  '5',
  'アクション-持続',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/資料庫'],
 ['御守り', '5', '財宝', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/御守り'],
 ['元手', '5', '財宝', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/元手'],
 ['冠', '5', 'アクション', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/冠'],
 ['技術者',
  '<4>*1',
  'アクション',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/技術者'],
 ['王室の鍛冶屋',
  '<8>',
  'アクション',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/王室の鍛冶屋'],
 ['市街', '<8>', 'アクション', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/市街'],
 ['ドルイド',
  '2',
  'アクション-幸運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ドルイド'],
 ['ピクシー',
  '2',
  'アクション-幸運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ピクシー'],
 ['追跡者',
  '2',
  'アクション-幸運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/追跡者'],
 ['修道院', '2', '夜行', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/修道院'],
 ['守護者', '2', '夜行', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/守護者'],
 ['忠犬',
  '2',
  'アクション-リアクション',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/忠犬'],
 ['愚者',
  '3',
  'アクション-幸運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/愚者'],
 ['レプラコーン',
  '3',
  'アクション-不運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/レプラコーン'],
 ['秘密の洞窟',
  '3',
  'アクションｰ持続',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/秘密の洞窟'],
 ['取り替え子',
  '3',
  '夜行',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/取り替え子'],
 ['夜警', '3', '夜行', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/夜警'],
 ['ゴーストタウン',
  '3',
  '夜行',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ゴーストタウン'],
 ['詩人',
  '4',
  'アクション-幸運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/詩人'],
 ['恵みの村',
  '4',
  'アクション-幸運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/恵みの村'],
 ['コンクラーベ',
  '4',
  'アクション',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/コンクラーベ'],
 ['ネクロマンサー',
  '4',
  'アクション',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/ネクロマンサー'],
 ['羊飼い',
  '4',
  'アクション',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/羊飼い'],
 ['暗躍者',
  '4',
  'アクション-アタック-不運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/暗躍者'],
 ['墓地', '4', '勝利点', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/墓地'],
 ['悪魔の工房',
  '4',
  '夜行',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/悪魔の工房'],
 ['悪魔祓い', '4', '夜行', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/悪魔祓い'],
 ['呪われた村',
  '5',
  'アクション-不運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/呪われた村'],
 ['プーカ',
  '5',
  'アクション',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/プーカ'],
 ['聖なる木立ち',
  '5',
  'アクション-幸運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/聖なる木立ち'],
 ['迫害者',
  '5',
  'アクション-アタック-不運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/迫害者'],
 ['悲劇のヒーロー',
  '5',
  'アクション',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/悲劇のヒーロー'],
 ['人狼', '5', 'アクション', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/人狼'],
 ['吸血鬼',
  '5',
  'アタック-不運',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/吸血鬼'],
 ['納骨堂', '5', '夜行', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/納骨堂'],
 ['悪人のアジト',
  '5',
  '夜行',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/悪人のアジト'],
 ['カブラー', '5', '夜行', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/カブラー'],
 ['偶像', '5', '財宝-幸運', '夜想曲', '', True, 'https://wikiwiki.jp/dominiondeck/偶像'],
 ['夜襲',
  '6',
  '夜行-アタック',
  '夜想曲',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/夜襲']]

eventlist=[['借入', '0', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/借入'],
 ['探索', '0', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/探索'],
 ['施し', '0', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/施し'],
 ['保存', '1', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/保存'],
 ['移動遊園地',
  '2',
  'イベント',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/移動遊園地'],
 ['偵察隊', '2', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/偵察隊'],
 ['焚火', '3', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/焚火'],
 ['探検', '3', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/探検'],
 ['立案', '3', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/立案'],
 ['渡し船', '3', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/渡し船'],
 ['使節団', '4', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/使節団'],
 ['巡礼', '4', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/巡礼'],
 ['海路', '5', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/海路'],
 ['奇襲', '5', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/奇襲'],
 ['交易', '5', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/交易'],
 ['舞踏会', '5', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/舞踏会'],
 ['失われた技術',
  '6',
  'イベント',
  '冒険',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/失われた技術'],
 ['鍛錬', '6', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/鍛錬'],
 ['相続', '7', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/相続'],
 ['誘導', '8', 'イベント', '冒険', '', True, 'https://wikiwiki.jp/dominiondeck/誘導'],
 ['昇進', '0', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/昇進'],
 ['掘進', '2', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/掘進'],
 ['徴税', '2', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/徴税'],
 ['宴会', '3', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/宴会'],
 ['儀式', '4', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/儀式'],
 ['大地への塩まき',
  '4',
  'イベント',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/大地への塩まき'],
 ['結婚式',
  '4+<3>',
  'イベント',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/結婚式'],
 ['意外な授かり物',
  '5',
  'イベント',
  '帝国',
  '',
  True,
  'https://wikiwiki.jp/dominiondeck/意外な授かり物'],
 ['征服', '6', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/征服'],
 ['制圧', '14', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/制圧'],
 ['凱旋', '<5>', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/凱旋'],
 ['寄付', '<8>', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/寄付'],
 ['併合', '<8>', 'イベント', '帝国', '', True, 'https://wikiwiki.jp/dominiondeck/併合']]

Card.objects.all().delete()
for card in cardlist:
    Card.objects.update_or_create(
    card_name=card[0],
    cost=card[1],
    genre=card[2],
    package=card[3],
    image=card[4],
    card_onoff=card[5],
    wikilink=card[6],
    )
